// <auto-generated />
namespace FirstExample.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RecreatedDBNEW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecreatedDBNEW));
        
        string IMigrationMetadata.Id
        {
            get { return "201812170358325_RecreatedDBNEW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
